[package]
name = "rsxm-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rsxm-core = { path = "../rsxm-core" }
rsxm-config = { path = "../rsxm-config" }
rsxm-rules = { path = "../rsxm-rules" }
rsxm-tun = { path = "../rsxm-tun" }
serde_json = "1"

[[bin]]
name = "rsxm-agent"
path = "src/main.rs"
